"""Levels 13–30 for Guess the Scoreline curated pool (embedded in JSON build)."""


def get_levels_13_30(mk):
    """Return [[level13], …, [level30]] — mk is the Question dict builder."""
    # fmt: off
    return [
        # Level 13 — 1998 highlights
        [
            mk(13, 1, 1998, "France 🇫🇷", "South Africa 🇿🇦", "GROUP STAGE", ("2-0", "3-0", "3-1", "4-0"), "B", "medium", "Marseilles; SA’s maiden venture.", "Host nation depth against debutants."),
            mk(13, 2, 1998, "England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Tunisia 🇹🇳", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "medium", "Shearer and Scholes eased England.", "Three Lions find rhythm."),
            mk(13, 3, 1998, "Spain 🇪🇸", "Nigeria 🇳🇬", "GROUP STAGE", ("2-2", "2-3", "1-2", "3-3"), "B", "medium", "Nantes shock; Ikpeba’s night.", "La Roja crumble against Green Eagles."),
            mk(13, 4, 1998, "Brazil 🇧🇷", "Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿", "OPENING MATCH", ("1-0", "2-1", "1-1", "2-0"), "B", "medium", "St-Denis carnival begins.", "Ronaldo’s carnival starts brightly."),
            mk(13, 5, 1998, "Germany 🇩🇪", "USA 🇺🇸", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "medium", "Klinsmann’s machine purrs in Lens.", "Stars & Stripes outclassed."),
            mk(13, 6, 1998, "Netherlands 🇳🇱", "Argentina 🇦🇷", "QUARTER-FINAL", ("1-1", "2-1", "1-0", "2-0"), "B", "medium", "Oranje edge past Batistuta’s crew.", "Bergkamp artistry in Marseille."),
            mk(13, 7, 1998, "Italy 🇮🇹", "Austria 🇦🇹", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-2"), "A", "medium", "St-Etienne draw; stalemate honours.", "Baggio & company held."),
            mk(13, 8, 1998, "Argentina 🇦🇷", "Croatia 🇭🇷", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "medium", "Pamplona-esque tension settles thin.", "Pipo & Co on top."),
            mk(13, 9, 1998, "Netherlands 🇳🇱", "South Korea 🇰🇷", "GROUP STAGE", ("4-0", "5-0", "3-0", "6-0"), "B", "medium", "Marseilles rout; orange floodgates.", "Cocu and five-star spectacle."),
            mk(13, 10, 1998, "Brazil 🇧🇷", "Norway 🇳🇴", "GROUP STAGE", ("1-1", "1-2", "1-0", "2-1"), "B", "medium", "Rosenborg-esque upset stings Seleção.", "Tore André Flo & co spring surprise."),
        ],
        # Level 14 — 2014 & 2010 knockout depth (medium)
        [
            mk(14, 1, 2014, "Belgium 🇧🇪", "USA 🇺🇸", "ROUND OF 16", ("1-0", "2-1", "1-1", "2-0"), "B", "medium", "Salvador extra-time drama.", "De Bruyne & Lukaku in added time.", "aet"),
            mk(14, 2, 2010, "Uruguay 🇺🇾", "South Korea 🇰🇷", "ROUND OF 16", ("1-0", "2-1", "1-1", "2-0"), "B", "medium", "Port Elizabeth — Suárez & Forlán deliver.", "Taeguk Warriors fall just short."),
            mk(14, 3, 2014, "Uruguay 🇺🇾", "Costa Rica 🇨🇷", "GROUP STAGE", ("1-1", "1-3", "0-2", "1-2"), "B", "medium", "Fortaleza upset; without Suárez.", "Campbell & Los Ticos run riot."),
            mk(14, 4, 2010, "Germany 🇩🇪", "Australia 🇦🇺", "GROUP STAGE", ("3-0", "4-0", "2-0", "5-0"), "B", "medium", "Durban blitz vs Socceroos.", "Özil & Klose orchestrate."),
            mk(14, 5, 2014, "Switzerland 🇨🇭", "France 🇫🇷", "GROUP STAGE", ("1-5", "2-5", "2-4", "3-5"), "B", "medium", "Salvador goal rush; Les Bleus rampant.", "Benzema at the carnival."),
            mk(14, 6, 2010, "South Africa 🇿🇦", "France 🇫🇷", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "medium", "Bloemfontein farewell shocker.", "Hosts bow out—but not quietly."),
            mk(14, 7, 2014, "Germany 🇩🇪", "Ghana 🇬🇭", "GROUP STAGE", ("1-1", "2-2", "1-2", "0-0"), "B", "medium", "Fortaleza ding-dong thriller.", "Götze salvages Schwarz Gelb."),
            mk(14, 8, 2010, "Greece 🇬🇷", "Nigeria 🇳🇬", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "medium", "Bloemfontein — Samaras & Dimitris deliver.", "Super Eagles undone."),
            mk(14, 9, 2014, "Netherlands 🇳🇱", "Chile 🇨🇱", "GROUP STAGE", ("1-0", "2-0", "0-0", "3-0"), "B", "medium", "São Paulo top-of-group showdown.", "Fer & Depay sub impact."),
            mk(14, 10, 2010, "Japan 🇯🇵", "Denmark 🇩🇰", "GROUP STAGE", ("2-1", "3-1", "2-0", "3-0"), "B", "medium", "Rustenburg duel for second.", "Daniel Agger-era Danes victorious."),
        ],
        # Level 15 — 2006 & 2002 drama
        [
            mk(15, 1, 2006, "Sweden 🇸🇪", "England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", "GROUP STAGE", ("1-1", "2-2", "1-2", "0-0"), "B", "medium", "Cologne group finale; Joe Cole’s volley.", "Gerrard grabs a point for Sven’s men."),
            mk(15, 2, 2002, "Mexico 🇲🇽", "Italy 🇮🇹", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "medium", "Oita — Azurri depth vs Tricolor.", "Jared Borgetti header answers Vieri."),
            mk(15, 3, 2006, "Spain 🇪🇸", "Ukraine 🇺🇦", "GROUP STAGE", ("3-0", "4-0", "2-0", "5-0"), "B", "medium", "Leipzig red machine; David Villa hat-trick fuel.", "Historic margin for La Roja."),
            mk(15, 4, 2002, "Spain 🇪🇸", "Republic of Ireland 🇮🇪", "ROUND OF 16", ("0-0", "1-1", "1-0", "2-2"), "B", "medium", "Suwon extra time then Penney shootout.", "Keane & Harte carry Tricolour dream.", "pens"),
            mk(15, 5, 2006, "Switzerland 🇨🇭", "Ukraine 🇺🇦", "ROUND OF 16", ("1-1", "0-0", "0-1", "1-0"), "B", "medium", "Cologne chess match then spot-kicks.", "Shevchenko sees one saved by Streller drama.", "pens"),
            mk(15, 6, 2002, "Costa Rica 🇨🇷", "Brazil 🇧🇷", "GROUP STAGE", ("1-5", "2-5", "2-4", "3-5"), "B", "medium", "Ronaldo at the Pantanal — five-hit Seleção.", "Edmilson overhead lives on highlight reels."),
            mk(15, 7, 2006, "Croatia 🇭🇷", "Australia 🇦🇺", "GROUP STAGE", ("1-1", "2-2", "1-2", "0-0"), "B", "medium", "Stuttgart six-pointer; Harry Kewell equaliser.", "Šimunić-era drama."),
            mk(15, 8, 2002, "South Africa 🇿🇦", "Spain 🇪🇸", "GROUP STAGE", ("1-3", "2-3", "2-2", "1-2"), "B", "medium", "Daejeon goals galore.", "Nomvethe & Fortune answer Raúl & Mendieta-era flair."),
            mk(15, 9, 2006, "Netherlands 🇳🇱", "Argentina 🇦🇷", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "medium", "Frankfurt chess match; Heinze shackles Robben.", "No quarter given between Oranje and Albiceleste."),
            mk(15, 10, 2002, "Japan 🇯🇵", "Turkey 🇹🇷", "ROUND OF 16", ("1-1", "0-1", "1-0", "0-2"), "B", "medium", "Miyagi heartbreak vs Şenoğlu’s troops.", "Umit Davala decides before extra time."),
        ],
        # Level 16 — 1998 group battles & R16 highlights
        [
            mk(16, 1, 1998, "France 🇫🇷", "Denmark 🇩🇰", "GROUP STAGE", ("1-0", "2-1", "2-0", "1-1"), "B", "medium", "Lyon group clincher.", "Lambert-era Danes undone by Petit & Deschamps flair."),
            mk(16, 2, 1998, "Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Morocco 🇲🇦", "GROUP STAGE", ("0-2", "0-3", "1-2", "1-3"), "B", "medium", "St-Étienne upset; Hadji runs riot.", "Scotland rue missed chances."),
            mk(16, 3, 1998, "Argentina 🇦🇷", "Jamaica 🇯🇲", "GROUP STAGE", ("4-0", "5-0", "3-0", "6-0"), "B", "medium", "Batistuta treble headline in Paris outskirts.", "Reggae Boys outgunned."),
            mk(16, 4, 1998, "USA 🇺🇸", "Iran 🇮🇷", "GROUP STAGE", ("0-1", "1-2", "1-1", "0-2"), "B", "medium", "Lyon geopolitical derby.", "Goals pay lip service to diplomacy."),
            mk(16, 5, 1998, "Belgium 🇧🇪", "Mexico 🇲🇽", "GROUP STAGE", ("1-1", "2-2", "1-2", "0-0"), "B", "medium", "Paris draw bursts Blanco-era bubble.", "Wilmots equalises."),
            mk(16, 6, 1998, "Japan 🇯🇵", "Argentina 🇦🇷", "GROUP STAGE", ("0-0", "0-1", "1-1", "0-2"), "B", "medium", "Toulouse test for Blue Samurai debut.", "Batistuta settles it."),
            mk(16, 7, 1998, "Yugoslavia 🇷🇸", "Germany 🇩🇪", "GROUP STAGE", ("1-1", "2-2", "2-1", "1-2"), "B", "medium", "Lens six-goal spectacle.", "Bierhoff steals headlines."),
            mk(16, 8, 1998, "Italy 🇮🇹", "Norway 🇳🇴", "ROUND OF 16", ("0-0", "1-0", "2-0", "1-1"), "B", "medium", "Marseilles cagey knockout.", "Christian Vieri ghost run decides."),
            mk(16, 9, 1998, "Brazil 🇧🇷", "Chile 🇨🇱", "ROUND OF 16", ("3-1", "4-1", "3-0", "4-0"), "B", "medium", "Ronaldo & César Sampaio power Seleção.", "Salas can’t keep up."),
            mk(16, 10, 1998, "Germany 🇩🇪", "Mexico 🇲🇽", "ROUND OF 16", ("1-1", "2-1", "2-0", "1-0"), "B", "medium", "Montpellier thriller; Bierhoff head.", "Luis Hernández effort not enough."),
        ],
        # Level 17 — mixed era results
        [
            mk(17, 1, 2014, "Croatia 🇭🇷", "Mexico 🇲🇽", "GROUP STAGE", ("0-3", "1-3", "1-2", "0-2"), "B", "medium", "Recife humbling for Modrić’s crew.", "Chicharito & Vela counter on the break."),
            mk(17, 2, 2010, "Switzerland 🇨🇭", "Spain 🇪🇸", "GROUP STAGE", ("0-0", "1-0", "1-1", "0-1"), "B", "medium", "Durban shock; Gelson Fernandes pounces.", "La Roja’s only group blemish."),
            mk(17, 3, 2006, "Italy 🇮🇹", "USA 🇺🇸", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "medium", "Kaiserslautern stalemate; Zaccardo own goal.", "McBride header brings parity."),
            mk(17, 4, 2002, "Uruguay 🇺🇾", "Senegal 🇸🇳", "GROUP STAGE", ("2-2", "3-3", "2-3", "1-2"), "B", "medium", "Suwon shootout feel without pens.", "Fadiga & Camara trade blows."),
            mk(17, 5, 1998, "Romania 🇷🇴", "England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "medium", "Toulouse Hagi magic vs Beckham free-kicks.", "Moldovan chips break English hearts."),
            mk(17, 6, 2014, "South Korea 🇰🇷", "Algeria 🇩🇿", "GROUP STAGE", ("1-4", "2-4", "2-3", "1-3"), "B", "medium", "Porto Alegre goal fest.", "Slimani & Feghouli run wild."),
            mk(17, 7, 2010, "Ghana 🇬🇭", "Australia 🇦🇺", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "medium", "Rustenburg honours even.", "Gyan & Shipyard stalemate storyline."),
            mk(17, 8, 2006, "England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Trinidad & Tobago 🇹🇹", "GROUP STAGE", ("1-0", "2-0", "3-0", "0-0"), "B", "medium", "Nuremberg labour vs Sparrowhawks.", "Crouch finally breaches Shaka Hislop."),
            mk(17, 9, 2002, "Brazil 🇧🇷", "Belgium 🇧🇪", "ROUND OF 16", ("1-0", "2-0", "2-1", "3-0"), "B", "medium", "Kobe knockout; Rivaldo double.", "Belgium’s golden gen halted."),
            mk(17, 10, 1998, "Brazil 🇧🇷", "Morocco 🇲🇦", "GROUP STAGE", ("2-0", "3-0", "4-0", "3-1"), "B", "medium", "Ronaldo at his elastic best in Paris.", "Chippo red mist helps Seleção cruise."),
        ],
        # Level 18 — Tactical battles
        [
            mk(18, 1, 2014, "Nigeria 🇳🇬", "Argentina 🇦🇷", "GROUP STAGE", ("1-3", "2-3", "2-2", "1-2"), "B", "medium", "Porto Alegre comeback; Messi orchestrates.", "Musa’s brace not enough for Super Eagles."),
            mk(18, 2, 2010, "Chile 🇨🇱", "Spain 🇪🇸", "GROUP STAGE", ("0-2", "1-2", "1-1", "0-1"), "A", "medium", "Pretoria procession; tiki-taka lesson.", "David Villa & Iniesta combine."),
            mk(18, 3, 2006, "Portugal 🇵🇹", "Mexico 🇲🇽", "GROUP STAGE", ("1-0", "2-1", "1-1", "2-0"), "B", "medium", "Simão & Maniche edge Gelsenkirchen duel.", "Owens-era El Tri fall short."),
            mk(18, 4, 2002, "Portugal 🇵🇹", "Poland 🇵🇱", "GROUP STAGE", ("3-0", "4-0", "2-0", "5-0"), "B", "medium", "Pauleta hat-trick in Jeonju rout.", "Selecção flex qualifying muscle."),
            mk(18, 5, 1998, "France 🇫🇷", "Saudi Arabia 🇸🇦", "GROUP STAGE", ("3-0", "4-0", "2-0", "5-0"), "B", "medium", "Henry & Trezeguet tear through Green Falcons.", "Saint-Denis statement win."),
            mk(18, 6, 2014, "Honduras 🇭🇳", "Ecuador 🇪🇨", "GROUP STAGE", ("0-2", "1-2", "1-1", "0-1"), "B", "medium", "Curitiba CONCACAF duel; Valencia brothers.", "Enner Valencia brace decides."),
            mk(18, 7, 2010, "Netherlands 🇳🇱", "Japan 🇯🇵", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "medium", "Van Persie settles Durban chess match.", "Samurai Blue can’t pierce organised Dutch block."),
            mk(18, 8, 2006, "Brazil 🇧🇷", "Croatia 🇭🇷", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "medium", "Kaká curler edges Berlin reunion.", "Modrić’s first dance with Seleção steel."),
            mk(18, 9, 2002, "Germany 🇩🇪", "Cameroon 🇨🇲", "GROUP STAGE", ("1-0", "2-0", "2-1", "3-0"), "B", "medium", "Shizuoka duel; Marco Bode overlaps.", "Eto’o can’t ignite Indomitable fightback."),
            mk(18, 10, 1998, "Spain 🇪🇸", "Paraguay 🇵🇾", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "medium", "Saint-Étienne chess match opener.", "Chilavert-era defence frustrates Hierro-era Spain."),
        ],
        # Level 19 — Unexpected scorers (medium)
        [
            mk(19, 1, 2014, "Japan 🇯🇵", "Ivory Coast 🇨🇮", "GROUP STAGE", ("1-1", "1-2", "0-1", "0-2"), "B", "medium", "Recife duel; Drogba-era counter.", "Kalou taps from Gervinho service."),
            mk(19, 2, 2010, "North Korea 🇰🇵", "Brazil 🇧🇷", "GROUP STAGE", ("0-2", "1-2", "0-1", "1-3"), "B", "medium", "Ellis Park keepsake NK goal sparks joy.", "Maicon & Élano finish the schooling."),
            mk(19, 3, 2006, "Argentina 🇦🇷", "Ivory Coast 🇨🇮", "GROUP STAGE", ("1-0", "2-1", "2-0", "3-1"), "B", "medium", "Hamburg tika with Crespo predator.", "Drogba’s opener answered by classic Albiceleste."),
            mk(19, 4, 2002, "Italy 🇮🇹", "Ecuador 🇪🇨", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "medium", "Sapporo opening salvo; Vieri punishes.", "Tricolor outgunned by Gli Azzurri intensity."),
            mk(19, 5, 1998, "England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Colombia 🇨🇴", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "medium", "Lens head-to-head; young Owen pace.", "Beckham free-kick narrative begins."),
            mk(19, 6, 2014, "Greece 🇬🇷", "Ivory Coast 🇨🇮", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "medium", "Fortaleza must-win swirl.", "Samaras & historic passage on goal difference."),
            mk(19, 7, 2010, "Slovakia 🇸🇰", "New Zealand 🇳🇿", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "medium", "Rustenburg share for All Whites folklore.", "Winston Reid header caps fightback."),
            mk(19, 8, 2006, "France 🇫🇷", "Togo 🇹🇬", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "medium", "Cologne cleanse after mutiny storyline.", "Henry brace restores order."),
            mk(19, 9, 2002, "Senegal 🇸🇳", "Denmark 🇩🇰", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "medium", "Daegu honours even after Lions shock opener.", "Tomasson can’t punish on the day."),
            mk(19, 10, 1998, "Croatia 🇭🇷", "Japan 🇯🇵", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "medium", "Nantes chess match decides Group H.", "Suker penalty edges Blue Samurai."),
        ],
        # Level 20 — Tournament endings (medium)
        [
            mk(20, 1, 2014, "France 🇫🇷", "Nigeria 🇳🇬", "ROUND OF 16", ("1-0", "2-0", "3-0", "2-1"), "B", "medium", "Brasília march; Paul Pogba thunder header.", "Enyeama heroics undone late."),
            mk(20, 2, 2010, "Portugal 🇵🇹", "Ivory Coast 🇨🇮", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "medium", "Port Elizabeth stalemate settles Group G.", "Ronaldo’s tournament finally ignites."),
            mk(20, 3, 2006, "Ukraine 🇺🇦", "Tunisia 🇹🇳", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "medium", "Berlin control; Blokhin-era steel.", "Shotsenkovsky cleans sheet narrative."),
            mk(20, 4, 2002, "Belgium 🇧🇪", "Russia 🇷🇺", "GROUP STAGE", ("2-2", "3-2", "2-1", "3-1"), "B", "medium", "Saitama six-goal seesaw thriller.", "Walem & Sonck edge Red Devils."),
            mk(20, 5, 1998, "Germany 🇩🇪", "Iran 🇮🇷", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "medium", "Montpellier ruthlessness.", "Klinsmann-era press overwhelms."),
            mk(20, 6, 2014, "Portugal 🇵🇹", "Ghana 🇬🇭", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "medium", "Brasília roller-coaster; Ronaldo grabs lifeline.", "Boye own goal subplot amid Black Stars drama."),
            mk(20, 7, 2010, "Paraguay 🇵🇾", "Japan 🇯🇵", "ROUND OF 16", ("1-1", "0-0", "1-0", "0-1"), "B", "medium", "Pretoria deadlock then Paraguay win the shoot-out.", "Cardozo buries decisive spot-kick.", "pens"),
            mk(20, 8, 2006, "Spain 🇪🇸", "France 🇫🇷", "ROUND OF 16", ("1-2", "1-3", "1-1", "0-2"), "B", "medium", "Hannover heartbreak vs Zidane composure.", "Vieira springs Henry for clincher."),
            mk(20, 9, 2002, "Uruguay 🇺🇾", "France 🇫🇷", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "medium", "Busan bore draw as holders flop.", "Les Bleus exit without scoring knockout."),
            mk(20, 10, 1998, "Paraguay 🇵🇾", "Nigeria 🇳🇬", "GROUP STAGE", ("2-1", "3-1", "2-0", "3-0"), "B", "medium", "Toulouse scramble; Celso Ayala heads early.", "Cardozo seals passage after Oruma leveller."),
        ],
        # Level 21 — Scoreline traps (hard)
        [
            mk(21, 1, 2014, "Switzerland 🇨🇭", "Ecuador 🇪🇨", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "hard", "Brasília see-saw; Seferovic last-gasp leveller?", "Actually Drmic & Mehmedi finish Swiss fightback."),
            mk(21, 2, 2006, "South Korea 🇰🇷", "Togo 🇹🇬", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "hard", "Frankfurt stamina test vs Sparrowhawks.", "Moon & Park flip Adebayor opener."),
            mk(21, 3, 1998, "Norway 🇳🇴", "Morocco 🇲🇦", "GROUP STAGE", ("1-1", "2-2", "1-2", "0-0"), "B", "hard", "Montpellier four-goal share.", "Håland Sr generation meets Hadji artistry."),
            mk(21, 4, 2002, "Tunisia 🇹🇳", "Belgium 🇧🇪", "GROUP STAGE", ("0-0", "1-1", "0-1", "1-0"), "B", "hard", "Oita chess match settles Group H.", "Wilmots can’t punish Carthage Eagles."),
            mk(21, 5, 2010, "Slovakia 🇸🇰", "Paraguay 🇵🇾", "GROUP STAGE", ("0-1", "0-2", "1-2", "0-0"), "D", "hard", "Bloemfontein duel for second.", "Possession stalemate honours goalkeepers."),
            mk(21, 6, 2006, "Angola 🇦🇴", "Portugal 🇵🇹", "GROUP STAGE", ("0-0", "0-1", "1-1", "0-2"), "B", "hard", "Cologne opener; Pauleta settles sibling derby.", "Ronaldo’s first WC dance begins."),
            mk(21, 7, 1998, "South Africa 🇿🇦", "Denmark 🇩🇰", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Toulouse parity on opening night continent.", "Bafana counter Tomasson menace."),
            mk(21, 8, 2014, "Bosnia-Herzegovina 🇧🇦", "Iran 🇮🇷", "GROUP STAGE", ("2-1", "3-1", "2-0", "3-0"), "B", "hard", "Salvador Balkan duel; Džeko & PJanić interplay.", "Quaresuma-esque finish from Džeko narrative."),
            mk(21, 9, 2002, "Spain 🇪🇸", "Slovenia 🇸🇮", "GROUP STAGE", ("2-1", "3-1", "2-0", "3-0"), "B", "hard", "Gwangju procession; Hierro-era control.", "Mori-era Slovenia fight but outclassed."),
            mk(21, 10, 2006, "Saudi Arabia 🇸🇦", "Tunisia 🇹🇳", "GROUP STAGE", ("1-1", "2-2", "1-2", "2-1"), "B", "hard", "Munich share spoils desert duel.", "Jaidi-era Tunisia scrap point."),
        ],
        # Levels 22–27 (hard mode)
        [
            mk(22, 1, 2014, "South Korea 🇰🇷", "Algeria 🇩🇿", "GROUP STAGE", ("1-3", "2-4", "2-3", "1-4"), "B", "hard", "Porto Alegre track meet.", "Slimani & Brahimi trade blows with AFC Tigers."),
            mk(22, 2, 2002, "Costa Rica 🇨🇷", "Turkey 🇹🇷", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Incheon honour even after drama.", "Hasan Sas spurns gilt edges."),
            mk(22, 3, 1998, "Jamaica 🇯🇲", "Japan 🇯🇵", "GROUP STAGE", ("1-0", "2-1", "1-1", "2-0"), "C", "hard", "Lyon reggae duel vs Blue Samurai.", "Whitmore & Gomez trade with Jo bullet."),
            mk(22, 4, 2010, "Nigeria 🇳🇬", "South Korea 🇰🇷", "GROUP STAGE", ("1-1", "2-2", "1-2", "2-1"), "B", "hard", "Durban frantic draw.", "Yakubu & Martins dance with Ki & Park."),
            mk(22, 5, 2006, "Iran 🇮🇷", "Mexico 🇲🇽", "GROUP STAGE", ("1-2", "1-3", "1-1", "0-2"), "B", "hard", "Hanover counter; Zinha & Borgetti haunt.", "Daei era bows out tame."),
            mk(22, 6, 2002, "South Africa 🇿🇦", "Paraguay 🇵🇾", "GROUP STAGE", ("1-1", "2-2", "1-2", "2-1"), "B", "hard", "Busan honours even for Bafana.", "Santa Cruz era Albirroja bunker."),
            mk(22, 7, 1998, "Chile 🇨🇱", "Austria 🇦🇹", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "St-Étienne stalemate duel.", "Salas versus Pfeifenberger subplot."),
            mk(22, 8, 2014, "USA 🇺🇸", "Ghana 🇬🇭", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "D", "hard", "Natal thriller; Clint & Brooks.", "Gyasi & Ayew duel late gut punch."),
            mk(22, 9, 2006, "Japan 🇯🇵", "Brazil 🇧🇷", "GROUP STAGE", ("0-3", "1-4", "1-3", "0-4"), "C", "hard", "Dortmund blue wall bursts.", "Ronaldo + Kaká symphony."),
            mk(22, 10, 2002, "Slovenia 🇸🇮", "Paraguay 🇵🇾", "GROUP STAGE", ("1-2", "1-3", "1-1", "0-2"), "B", "hard", "Seogwipo knockout tie.", "Santa Cruz brace buries Balkan rookies."),
        ],
        # Level 23 — The 0-0 / 1-0 maze (hard)
        [
            mk(23, 1, 2010, "France 🇫🇷", "Uruguay 🇺🇾", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Cape Town duel of titans stalls.", "Lodeiro & Ribéry trade half-chances only."),
            mk(23, 2, 2002, "France 🇫🇷", "Senegal 🇸🇳", "OPENING MATCH", ("0-0", "0-1", "1-1", "1-0"), "B", "hard", "Seoul shock opens the tournament narrative.", "Papa Bouba Diop pounces."),
            mk(23, 3, 2014, "Mexico 🇲🇽", "Cameroon 🇨🇲", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "hard", "Natal humidity; Dos Santos & Oribe combine.", "Ochoa not needed but stars align."),
            mk(23, 4, 2006, "Angola 🇦🇴", "Mexico 🇲🇽", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Hanover bore draw denies goals.", "Rafa Márquez snuffs counter threats."),
            mk(23, 5, 1998, "Bulgaria 🇧🇬", "Paraguay 🇵🇾", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Montpellier chess match honours keepers.", "Stoičkov-lite era struggles."),
            mk(23, 6, 2010, "Algeria 🇩🇿", "Slovenia 🇸🇮", "GROUP STAGE", ("0-0", "0-1", "1-1", "1-0"), "A", "hard", "Polokwane cat’s cradle for Group C.", "Chaouchi night not enough for Fennec Foxes."),
            mk(23, 7, 2002, "Sweden 🇸🇪", "England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Saitama chess match; Ljungberg vs Beckham.", "Anders Svensson free-kick equaliser."),
            mk(23, 8, 2014, "Iran 🇮🇷", "Nigeria 🇳🇬", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Curitiba midfield grind ends goalless.", "Moses & Dejagah spar without breach."),
            mk(23, 9, 2006, "Trinidad & Tobago 🇹🇹", "Sweden 🇸🇪", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Dortmund Caribbean wall frustrates Blågult.", "Shaka Hislop hero hours."),
            mk(23, 10, 1998, "Japan 🇯🇵", "Croatia 🇭🇷", "GROUP STAGE", ("1-1", "0-1", "0-0", "1-0"), "B", "hard", "Nantes opener; Suker punishes after half-time.", "Blue Samurai cannot hold Vlaović menace."),
        ],
        # Level 24 — Forgotten battles (hard)
        [
            mk(24, 1, 2002, "Ecuador 🇪🇨", "Croatia 🇭🇷", "GROUP STAGE", ("0-0", "1-0", "1-1", "0-1"), "B", "hard", "Niigata chess match; Édú edges Dado Pršo.", "Acosta marshals Andean wall."),
            mk(24, 2, 1998, "Chile 🇨🇱", "Italy 🇮🇹", "GROUP STAGE", ("1-1", "2-2", "1-2", "2-1"), "B", "hard", "Bordeaux six-fold drama between CONMEBOL & Azzurri.", "Salas vs Vieri shootout."),
            mk(24, 3, 2010, "New Zealand 🇳🇿", "Italy 🇮🇹", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Nelspruit All Whites steal point vs holders.", "Smeltz answers Iaquinta."),
            mk(24, 4, 2006, "Saudi Arabia 🇸🇦", "Ukraine 🇺🇦", "GROUP STAGE", ("0-3", "0-4", "1-4", "0-5"), "B", "hard", "Hamburg shellacking; Shevchenko showcase.", "Blokhin’s boys annihilate Green Falcons."),
            mk(24, 5, 2014, "Algeria 🇩🇿", "Russia 🇷🇺", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Curitiba track meet after cooling break.", "Kokorin & Mbia trade mental lapses."),
            mk(24, 6, 2002, "Poland 🇵🇱", "USA 🇺🇸", "GROUP STAGE", ("2-1", "3-1", "2-0", "3-0"), "B", "hard", "Jeonju shootout; Olisadebe & Krzynówek star.", "Donovan can’t spark enough."),
            mk(24, 7, 1998, "Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Norway 🇳🇴", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "A", "hard", "Bordeaux bore draw ends both hopes.", "Sørloth & Collins cancel out."),
            mk(24, 8, 2010, "Serbia 🇷🇸", "Australia 🇦🇺", "GROUP STAGE", ("1-1", "1-2", "0-2", "0-1"), "B", "hard", "Nelspruit Balkan wall breaks Socceroos hearts.", "Pantelić & Krasić edge Holger’s men."),
            mk(24, 9, 2006, "Serbia & Montenegro 🇷🇸", "Ivory Coast 🇨🇮", "GROUP STAGE", ("2-2", "2-3", "1-3", "2-1"), "B", "hard", "Munich eleven-goal thriller.", "Drogba & Kalou power Elephants rally."),
            mk(24, 10, 2002, "South Korea 🇰🇷", "USA 🇺🇸", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Daegu honour shared with hosts.", "Clint Mathis answers Ahn’s opener."),
        ],
        # Level 25 — Tight margins (hard)
        [
            mk(25, 1, 2014, "Ecuador 🇪🇨", "France 🇫🇷", "GROUP STAGE", ("1-1", "0-0", "0-1", "1-0"), "B", "hard", "Maracanã dead rubber still matters for fair play.", "Neither side risks more than a point."),
            mk(25, 2, 2006, "Croatia 🇭🇷", "Japan 🇯🇵", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Kaiserslautern midfield grind.", "Modrić’s first taste of Samurai blue steel."),
            mk(25, 3, 1998, "Colombia 🇨🇴", "Tunisia 🇹🇳", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "hard", "Montpellier Latin flair edges North Africa.", "Valderrama sets rhythm still."),
            mk(25, 4, 2010, "Uruguay 🇺🇾", "France 🇫🇷", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Cape Town cagey rematch of ‘10 narrative.", "Domenech’s side already broken."),
            mk(25, 5, 2002, "Mexico 🇲🇽", "Croatia 🇭🇷", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "hard", "Niigata chess match; Borgetti edges Blanco service.", "Šuker generation sunset."),
            mk(25, 6, 2014, "Ivory Coast 🇨🇮", "Colombia 🇨🇴", "GROUP STAGE", ("1-1", "1-2", "0-2", "2-2"), "D", "hard", "Brasília James Rodríguez masterpiece night.", "Drogba & Gervinho can’t outscore Cafeteros."),
            mk(25, 7, 2006, "Sweden 🇸🇪", "Paraguay 🇵🇾", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "D", "hard", "Berlin midfield slog ends square.", "Ljunberg & Santa Cruz nullify."),
            mk(25, 8, 1998, "Belgium 🇧🇪", "South Korea 🇰🇷", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Paris stalemate as both advance math.", "Wilmots & Yoo Sang-chul trade blows."),
            mk(25, 9, 2010, "Spain 🇪🇸", "Honduras 🇭🇳", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "hard", "Johannesburg ball-hogging lesson.", "Villa brace buries Catrachos."),
            mk(25, 10, 2006, "Italy 🇮🇹", "Croatia 🇭🇷", "GROUP STAGE", ("0-1", "1-2", "1-1", "0-2"), "C", "hard", "Hamburg chess match; Pirlo & Modrić duet.", "Materazzi & Simunic subplot."),
        ],
        # Level 26 — “Did that happen?” scores (hard)
        [
            mk(26, 1, 2014, "Honduras 🇭🇳", "Switzerland 🇨🇭", "GROUP STAGE", ("0-2", "0-3", "1-3", "0-4"), "B", "hard", "Manaus Shaqiri hat-trick humbles Catrachos.", "Xhaka & Inler boss midfield."),
            mk(26, 2, 2006, "South Korea 🇰🇷", "Switzerland 🇨🇭", "GROUP STAGE", ("0-1", "0-2", "1-2", "0-0"), "B", "hard", "Hanover precision from Frei & Barnetta.", "Park can’t spark enough."),
            mk(26, 3, 1998, "Austria 🇦🇹", "Cameroon 🇨🇲", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Toulouse tactical stalemate.", "Song & Wome trade nervy moments."),
            mk(26, 4, 2010, "South Korea 🇰🇷", "Greece 🇬🇷", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "hard", "Port Elizabeth Asian press overwhelms Euro 2004 kings.", "Ki & Park run midfield."),
            mk(26, 5, 2002, "Costa Rica 🇨🇷", "China PR 🇨🇳", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "hard", "Gwangju counter; Wanchope & China own goal.", "Sun Jihai cannot contain Ticos pace."),
            mk(26, 6, 1998, "Germany 🇩🇪", "Yugoslavia 🇷🇸", "GROUP STAGE", ("1-1", "2-2", "1-2", "2-1"), "B", "hard", "Lens six-goal Balkan-German theatre.", "Mijatović vs Bierhoff shootout."),
            mk(26, 7, 2014, "Russia 🇷🇺", "South Korea 🇰🇷", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Cuiabá humidity draw.", "Keun-ho & Kanibolotskiy trade half-chances."),
            mk(26, 8, 2006, "Czech Republic 🇨🇿", "Ghana 🇬🇭", "GROUP STAGE", ("1-1", "0-2", "0-1", "1-2"), "C", "hard", "Cologne African counter blitz.", "Asamoah Gyan & Muntari expose Rosický injuries."),
            mk(26, 9, 2010, "Cameroon 🇨🇲", "Denmark 🇩🇰", "GROUP STAGE", ("1-1", "1-2", "0-2", "2-1"), "C", "hard", "Pretoria Nordic resolve vs Indomitable chaos.", "Rommedahl & Bendtner nick it."),
            mk(26, 10, 1998, "Morocco 🇲🇦", "Brazil 🇧🇷", "GROUP STAGE", ("0-2", "0-3", "1-3", "0-4"), "B", "hard", "Nantes Seleção cruise; Ronaldo brace.", "Hadji can’t lift Atlas Lions."),
        ],
        # Level 27 — Tricky mid-table (hard)
        [
            mk(27, 1, 2014, "Nigeria 🇳🇬", "Bosnia-Herzegovina 🇧🇦", "GROUP STAGE", ("0-0", "1-0", "1-1", "2-1"), "B", "hard", "Cuiabá Emenike & Odemwingie finish.", "Džeko handball heartbreak ruled out."),
            mk(27, 2, 2002, "Tunisia 🇹🇳", "Japan 🇯🇵", "GROUP STAGE", ("0-1", "0-2", "1-2", "0-0"), "B", "hard", "Osaka Blue Samurai press suffocates Eagles of Carthage.", "Nakata pulls strings."),
            mk(27, 3, 1998, "Paraguay 🇵🇾", "Spain 🇪🇸", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Saint-Étienne catenaccio classic.", "Zubizarreta meets Chilavert script."),
            mk(27, 4, 2010, "Australia 🇦🇺", "Serbia 🇷🇸", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "hard", "Nelspruit Tim Cahill sequel vs Stanković era.", "Holman chip seals Socceroos surge."),
            mk(27, 5, 2006, "Iran 🇮🇷", "Portugal 🇵🇹", "GROUP STAGE", ("0-1", "0-2", "1-2", "0-0"), "B", "hard", "Frankfurt counter; Deco & Figo unpick.", "Rahman Rezaei can’t hold width."),
            mk(27, 6, 2002, "Cameroon 🇨🇲", "Saudi Arabia 🇸🇦", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "hard", "Saitama Indomitable bounce-back.", "Eto’o double buries Green Falcons."),
            mk(27, 7, 1998, "South Korea 🇰🇷", "Mexico 🇲🇽", "GROUP STAGE", ("1-2", "1-3", "0-3", "2-3"), "B", "hard", "Lyon Blanco cartwheel game vs hosts.", "Hernández & Luna outpace tired legs."),
            mk(27, 8, 2014, "Algeria 🇩🇿", "Belgium 🇧🇪", "GROUP STAGE", ("0-1", "1-2", "1-1", "0-2"), "B", "hard", "Belo Horizonte class from Eden & Moussa.", "Fennec counters almost nick one."),
            mk(27, 9, 2010, "Japan 🇯🇵", "Cameroon 🇨🇲", "GROUP STAGE", ("0-0", "1-0", "2-0", "1-1"), "B", "hard", "Bloemfontein Honda & Endō edge Indomitable.", "Eto'o kept quiet."),
            mk(27, 10, 2006, "Italy 🇮🇹", "Czech Republic 🇨🇿", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "hard", "Hamburg group decider — Inzaghi settles.", "Nedved absence matters."),
        ],
        # Level 28 — Low visibility matches (hard)
        [
            mk(28, 1, 2014, "USA 🇺🇸", "Germany 🇩🇪", "GROUP STAGE", ("0-0", "0-1", "1-1", "0-2"), "B", "hard", "Recife gentleman's draw sends both through.", "Müller’s efficiency enough."),
            mk(28, 2, 2002, "Poland 🇵🇱", "South Korea 🇰🇷", "GROUP STAGE", ("0-1", "0-2", "1-2", "0-0"), "A", "hard", "Daejeon co-host miracle start.", "Yoo Sang-chool winner deafens terraces."),
            mk(28, 3, 1998, "Iran 🇮🇷", "Yugoslavia 🇷🇸", "GROUP STAGE", ("1-1", "0-1", "1-0", "0-2"), "B", "hard", "Saint-Étienne Balkan pragmatism prevails.", "Mijatović edges Mihajlović free-kicks."),
            mk(28, 4, 2010, "Brazil 🇧🇷", "Portugal 🇵🇹", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Durban chess match avoids yellow-card chaos.", "Ronaldo & Kaká politely share spoils."),
            mk(28, 5, 2006, "Paraguay 🇵🇾", "Trinidad & Tobago 🇹🇹", "GROUP STAGE", ("1-0", "2-0", "3-0", "1-1"), "B", "hard", "Kaiserslautern tame Soca Warriors fairy tale.", "Sancho & Birchall run into Santa Cruz bunker."),
            mk(28, 6, 2002, "Ecuador 🇪🇨", "Mexico 🇲🇽", "GROUP STAGE", ("1-1", "1-2", "0-2", "2-1"), "C", "hard", "Miyagi derby; Borgetti volley overshadows Kaviedes.", "Tricolor CONMEBOL edge."),
            mk(28, 7, 1998, "France 🇫🇷", "Paraguay 🇵🇾", "ROUND OF 16", ("2-0", "1-0", "0-0", "2-1"), "B", "hard", "Lens golden goal lore — Laurent Blanc settles.", "Chilavert cannot stop fate.", "aet"),
            mk(28, 8, 2014, "South Korea 🇰🇷", "Belgium 🇧🇪", "GROUP STAGE", ("0-0", "0-1", "1-1", "0-2"), "B", "hard", "São Paulo counter; Origi & Vertonghen blunt hosts.", "De Bruyne dictates tempo."),
            mk(28, 9, 2010, "New Zealand 🇳🇿", "Paraguay 🇵🇾", "GROUP STAGE", ("1-1", "0-0", "1-0", "0-1"), "B", "hard", "Polokwane All Whites storybook point.", "Nelson Mandela Bay pride."),
            mk(28, 10, 2006, "Mexico 🇲🇽", "Argentina 🇦🇷", "ROUND OF 16", ("1-1", "1-2", "0-2", "2-1"), "D", "hard", "Leipzig Sabella-era Albiceleste edge CONCACAF.", "Maxi Rodríguez extra-time dagger.", "aet"),
        ],
        # Level 29 — Obscure goal tally (hard)
        [
            mk(29, 1, 2014, "Colombia 🇨🇴", "Greece 🇬🇷", "GROUP STAGE", ("2-0", "3-0", "4-0", "3-1"), "B", "hard", "Belo Horizonte dancing James & Teo party.", "Gekas shackled."),
            mk(29, 2, 2002, "Russia 🇷🇺", "Tunisia 🇹🇳", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "hard", "Kobe Onopko & Titans edge African debut.", "Karpin service lines."),
            mk(29, 3, 1998, "Argentina 🇦🇷", "Japan 🇯🇵", "GROUP STAGE", ("2-0", "1-0", "0-0", "2-1"), "B", "hard", "Toulouse Batistuta head-start vs Blue Samurai.", "Sensational fan scenes."),
            mk(29, 4, 2010, "South Korea 🇰🇷", "Uruguay 🇺🇾", "ROUND OF 16", ("1-1", "1-2", "0-2", "2-1"), "B", "hard", "Port Elizabeth Suárez & Forlán combo.", "Ki & Lee can’t overturn Celeste edge."),
            mk(29, 5, 2006, "England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Paraguay 🇵🇾", "GROUP STAGE", ("2-0", "1-0", "0-0", "2-1"), "B", "hard", "Frankfurt Beckham deliveries vs Santa Cruz bunker.", "Crouch elbows controversy."),
            mk(29, 6, 2002, "Sweden 🇸🇪", "Nigeria 🇳🇬", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "hard", "Kobe Henrik Larsson duel vs Oliseh-era midfield.", "Anders Svensson free-kick lore."),
            mk(29, 7, 1998, "Netherlands 🇳🇱", "Mexico 🇲🇽", "GROUP STAGE", ("1-1", "2-2", "1-2", "3-3"), "B", "hard", "Saint-Étienne Volleyball scoreline honours.", "Zambrano-era cards fly."),
            mk(29, 8, 2014, "Cameroon 🇨🇲", "Brazil 🇧🇷", "GROUP STAGE", ("0-3", "1-4", "1-3", "0-4"), "C", "hard", "Brasília Neymar & Fred rout Indomitable meltdown.", "Song & Choupo punished."),
            mk(29, 9, 2010, "Honduras 🇭🇳", "Chile 🇨🇱", "GROUP STAGE", ("0-0", "0-1", "1-1", "0-2"), "B", "hard", "Nelspruit Bielsa gegenpress dismantles Catrachos.", "Suazo & Humberto core."),
            mk(29, 10, 2006, "Netherlands 🇳🇱", "Ivory Coast 🇨🇮", "GROUP STAGE", ("1-1", "2-1", "1-0", "2-0"), "B", "hard", "Stuttgart Robben vs Drogba heavyweight bout.", "van Persie curls beauty."),
        ],
        # Level 30 — Ultimate grind (hard)
        [
            mk(30, 1, 2014, "Germany 🇩🇪", "USA 🇺🇸", "GROUP STAGE", ("2-0", "1-0", "0-0", "2-1"), "B", "hard", "Recife gentleman's deal after Ghana chaos.", "Müller’s tap enough for reshuffled XI."),
            mk(30, 2, 2002, "Belgium 🇧🇪", "Japan 🇯🇵", "GROUP STAGE", ("1-1", "2-2", "1-2", "0-0"), "B", "hard", "Saitama Tricolor scramble vs Nakata-era Blue Samurai.", "Wilmots & Van der Heyden cancel Inamoto."),
            mk(30, 3, 1998, "Italy 🇮🇹", "Cameroon 🇨🇲", "GROUP STAGE", ("2-0", "3-0", "4-0", "3-1"), "B", "hard", "Montpellier Vieri bulldozer headline.", "Milla’s swansong can’t ignite."),
            mk(30, 4, 2010, "Slovakia 🇸🇰", "New Zealand 🇳🇿", "GROUP STAGE", ("0-0", "1-1", "1-0", "0-1"), "B", "hard", "Polokwane heart for All Whites.", "Vittek meets Smeltz duel."),
            mk(30, 5, 2006, "Togo 🇹🇬", "Switzerland 🇨🇭", "GROUP STAGE", ("0-1", "0-2", "1-2", "0-3"), "B", "hard", "Dortmund Tranquillo Barnetta brace buries Sparrows.", "Frei overlaps Adebayor fatigue."),
            mk(30, 6, 2002, "Russia 🇷🇺", "Japan 🇯🇵", "GROUP STAGE", ("1-1", "0-1", "0-0", "1-0"), "B", "hard", "Yokohoma Ono & Inamoto edge Sychev-era.", "Russia’s last stand in Group H."),
            mk(30, 7, 1998, "Germany 🇩🇪", "USA 🇺🇸", "GROUP STAGE", ("1-0", "2-0", "3-0", "2-1"), "B", "hard", "Paris German machine overwhelms naive States.", "Bierhoff & Klinsmann power."),
            mk(30, 8, 2014, "Australia 🇦🇺", "Spain 🇪🇸", "GROUP STAGE", ("0-2", "0-3", "1-3", "0-4"), "B", "hard", "Curitiba Aussie pride vs broken tiki remnants.", "Villa trio still ruthless."),
            mk(30, 9, 2010, "Denmark 🇩🇰", "Japan 🇯🇵", "GROUP STAGE", ("1-2", "1-3", "0-3", "2-3"), "D", "hard", "Rustenburg Honda & Endō haunt Danes.", "Agger & Poulsen overrun."),
            mk(30, 10, 2006, "Saudi Arabia 🇸🇦", "Spain 🇪🇸", "GROUP STAGE", ("0-0", "0-1", "0-2", "1-1"), "B", "hard", "Kaiserslautern Roja reserves still cruise.", "Joaquín & Raúl enjoy cameo."),
        ],
    ]
    # fmt: on
