/** Cameroon legends — 30 rows each: [diff, question, A, B, C, D, ans, h1, h2, h3] */
const R = (a) => a;

export const cameroon = {
  'samuel-etoo': R([
    ['easy', "At the 2010 World Cup, Samuel Eto'o scored a penalty against which opponent in the group stage?", 'Denmark', 'Netherlands', 'Paraguay', 'Japan', 'A', 'South Africa 2010', 'Group match', 'Denmark'],
    ['easy', "At the 2002 World Cup, Eto'o scored in Cameroon's 2-0 group win over which team?", 'Saudi Arabia', 'Germany', 'Ireland', 'Brazil', 'A', 'Korea/Japan', 'Group E', 'Saudi Arabia'],
    ['easy', "At the 2014 World Cup, which team did Cameroon face in their opening group match in Natal?", 'Mexico', 'Brazil', 'Croatia', 'Spain', 'A', 'Opening match', 'Group A', 'Mexico'],
    ['easy', "At the 1998 World Cup, Eto'o appeared as a substitute against which South American giant?", 'Brazil', 'France', 'Italy', 'Chile', 'A', 'France 98', 'Group B', 'Brazil'],
    ['easy', "At the 2002 World Cup, Eto'o started against Germany — what was the result?", 'Germany won 2-0', '1-1 draw', 'Cameroon won 1-0', '0-0', 'A', 'Group E', 'Korea/Japan', 'Germany won'],
    ['easy', "At the 2010 World Cup, Eto'o converted a penalty vs Denmark — how many goals did Cameroon score in total at that tournament?", 'One', 'Two', 'Three', 'Four', 'A', 'South Africa', 'All group', 'One'],
    ['easy', "At the 2014 World Cup, Eto'o assisted a goal against Brazil scored by which teammate?", 'Vincent Aboubakar', 'Choupo-Moting', 'Alex Song', 'Webó', 'A', 'Brasília', '4-1 loss', 'Aboubakar'],
    ['easy', "How many World Cup finals tournaments did Eto'o play in from 1998 to 2014?", 'Four', 'Three', 'Five', 'Two', 'A', 'France to Brazil', 'Finals only', 'Four'],
    ['easy', "At the 1998 World Cup, Cameroon shared Group B with Italy, Chile and which team?", 'Austria', 'Scotland', 'Norway', 'Paraguay', 'A', 'France 98', 'Draw', 'Austria'],
    ['easy', "At the 2010 World Cup, Eto'o captained Cameroon — true or false?", 'True', 'False', 'Only vs Japan', 'Only vs Netherlands', 'A', 'Captain', 'South Africa', 'True'],
    ['medium', "At the 1998 World Cup, Eto'o came on as a substitute in a draw with Austria — who scored Cameroon's goal?", 'Pierre Njanka', 'Patrick Mboma', 'Joseph-Desire Job', 'Rigobert Song', 'A', 'France 98', 'Group B', 'Njanka'],
    ['medium', "At the 1998 World Cup, Eto'o was an unused substitute in Cameroon's final group game against which team?", 'Chile', 'Italy', 'Austria', 'Brazil', 'A', 'France 98', 'Bench', 'Chile'],
    ['medium', "At the 2002 World Cup, Eto'o faced Ireland in a 1-1 draw — who scored Ireland's equaliser?", 'Matt Holland', 'Robbie Keane', 'Damien Duff', 'Jason McAteer', 'A', 'Niigata', 'Group E', 'Holland'],
    ['medium', "At the 2010 World Cup, Eto'o's penalty vs Denmark was Cameroon's only goal — who was Denmark's goalkeeper?", 'Thomas Sørensen', 'Kasper Schmeichel', 'Peter Schmeichel', 'Jesper Christiansen', 'A', 'Pretoria', 'Shot-stopper', 'Sørensen'],
    ['medium', "At the 2014 World Cup, Eto'o started against Mexico but was substituted early — Mexico won 1-0 with a goal from whom?", 'Oribe Peralta', 'Javier Hernández', 'Giovani dos Santos', 'Andrés Guardado', 'A', 'Natal', 'Group A', 'Peralta'],
    ['medium', "At the 1998 World Cup, Italy beat Cameroon 3-0 — who opened the scoring for Italy?", 'Christian Vieri', 'Roberto Baggio', 'Luigi Di Biagio', 'Paolo Maldini', 'A', 'Montpellier', 'Group B', 'Vieri'],
    ['medium', "At the 2002 World Cup, Eto'o played in a 0-0 draw with Ireland — which Irish goalkeeper kept a clean sheet?", 'Shay Given', 'Packie Bonner', 'Dean Kiely', 'Alan Kelly', 'A', 'Kashima', 'Group E', 'Given'],
    ['medium', "Between 1998 and 2014, Eto'o scored World Cup goals in which editions?", '2002 and 2010', '1998 and 2002', '2010 and 2014 only', '1998 only', 'A', 'Tally', 'Goals', '2002 and 2010'],
    ['medium', "At the 2014 World Cup, Eto'o faced Croatia in the group — Croatia won 4-0; who scored Croatia's first goal?", 'Ivica Olić', 'Ivan Perišić', 'Luka Modrić', 'Mario Mandžukić', 'A', 'Manaus', 'Group A', 'Olić'],
    ['medium', "At the 1998 World Cup, Eto'o replaced which striker when coming on vs Austria?", 'Patrick Mboma', 'Pierre Womé', 'Bruno N\'Gotty', 'Joseph-Desire Job', 'A', 'Substitution', 'France 98', 'Mboma'],
    ['hard', "At the 1934 World Cup, Egypt's Abdulrahman Fawzi scored against which opponent?", 'Hungary', 'Argentina', 'Netherlands', 'Sweden', 'A', 'Italy 34', 'African pioneer', 'Hungary'],
    ['hard', "At the 1954 World Cup, South Korea's Pak Doo-ik scored the winner against which team?", 'Italy', 'Hungary', 'Turkey', 'West Germany', 'A', 'Switzerland 54', 'Upset', 'Italy'],
    ['hard', "At the 1982 World Cup, Cameroon's first-ever World Cup goal was scored by whom against Peru?", 'Grégoire M\'Bida', 'Roger Milla', 'Théophile Abega', 'Jean Manga Onguéné', 'A', 'Spain 82', 'Historic', 'M\'Bida'],
    ['hard', "At the 1990 World Cup, François Omam-Biyik's header beat Argentina — who was Cameroon's goalkeeper?", 'Thomas N\'Kono', 'Joseph-Antoine Bell', 'Jacques Songo\'o', 'Luc Buys', 'A', 'Opening match', 'Italy 90', 'N\'Kono'],
    ['hard', "At the 1990 World Cup, Roger Milla scored twice vs Colombia in extra time — what was the final score?", '2-1 Cameroon', '1-1', '3-2 Colombia', '0-0', 'A', 'Round of 16', 'Naples', '2-1'],
    ['hard', "At the 1994 World Cup, Cameroon beat Saudi Arabia 2-1 — who scored Cameroon's first goal?", 'François Omam-Biyik', 'Roger Milla', 'Patrick Mboma', 'Hans Agbo', 'A', 'Dallas', 'Opening goal', 'Omam-Biyik'],
    ['hard', "At the 1934 World Cup, Egypt played in a round-robin — what was the scoreline against Hungary?", 'Hungary 4-2 Egypt', '2-2', '1-0 Egypt', '3-0 Hungary', 'A', 'Italy 34', 'First African WC', '4-2'],
    ['hard', "At the 1934 World Cup, Abdulrahman Fawzi scored against Hungary — how many goals did Fawzi score in that match?", 'Two', 'One', 'Three', 'Zero', 'A', 'Italy 34', 'Egypt scorer', 'Two'],
    ['hard', "At the 1934 World Cup, Egypt's first match was against which opponent?", 'Hungary', 'Argentina', 'Netherlands', 'Sweden', 'A', 'Italy 34', 'CAF pioneer', 'Hungary'],
    ['hard', "At the 1954 World Cup, South Korea lost 9-0 to which team in the group stage?", 'Hungary', 'West Germany', 'Turkey', 'Italy', 'A', 'Switzerland 54', 'Heavy defeat', 'Hungary'],
    ['hard', "At the 1954 World Cup, South Korea's Pak Doo-ik scored the winner vs Italy — Italy had won which previous World Cups?", 'Italy 1934 and 1938', 'None', '1934 only', '1950', 'A', 'History', 'Italy', 'Two titles'],
  ]),
  'roger-milla': R([
    ['easy', "In 1990, Roger Milla scored twice in extra time against Colombia in which round?", 'Round of 16', 'Quarter-finals', 'Group stage', 'Semi-finals', 'A', 'Italy 1990', 'Knockout', 'Round of 16'],
    ['easy', "In 1990, Roger Milla celebrated his goals against Colombia by dancing near what?", 'The corner flag', 'The centre circle', 'The dugout', 'The goal net', 'A', 'Iconic', 'Celebration', 'Corner flag'],
    ['easy', "In 1994, Roger Milla scored against Russia at age 42 — what record did that set at the time?", 'Oldest World Cup goalscorer', 'Fastest hat-trick', 'Most goals', 'Youngest scorer', 'A', 'USA 94', 'Record', 'Oldest'],
    ['easy', "In 1990, Roger Milla came off the bench to score twice against which team?", 'Colombia', 'Argentina', 'Romania', 'England', 'A', 'Italy 90', 'Substitute hero', 'Colombia'],
    ['easy', "At the 2002 World Cup, did Roger Milla appear in Cameroon's squad at the finals?", 'No — he was not selected', 'Yes', 'Only as coach', 'Only on standby', 'A', 'Korea/Japan', 'Retired from national team', 'Not in squad'],
    ['easy', "In 1990, Roger Milla's goals helped Cameroon eliminate Colombia — what was the score after extra time?", '2-1 Cameroon', '1-1', '3-2 Colombia', '0-0', 'A', 'Naples', 'Extra time', '2-1'],
    ['easy', "In 1994, Roger Milla's goal vs Russia made headlines because of his age — how old was he?", '42', '38', '40', '45', 'A', 'USA 94', 'Birth year', '42'],
    ['easy', "At the 1982 World Cup, Roger Milla appeared for Cameroon — Cameroon drew 0-0 with Peru in their opener — true?", 'True', 'False', 'Only in 1990', 'Only in 1994', 'A', 'Spain 82', 'Group', 'True'],
    ['easy', "In the 1990 quarter-final loss to England, how many goals did Gary Lineker score from the penalty spot?", 'Two', 'One', 'Three', 'Zero', 'A', 'Naples', 'Spot kicks', 'Two'],
    ['easy', "In 1990, Roger Milla's double vs Colombia came after he replaced which teammate?", 'Emmanuel Maboang', 'François Omam-Biyik', 'Louis-Paul M\'Fédé', 'Thomas Libiih', 'A', 'Substitution', 'Italy 90', 'Maboang'],
    ['medium', "In 1990, Roger Milla's first goal vs Colombia was assisted by a pass from whom?", 'Emmanuel Maboang', 'François Omam-Biyik', 'Thomas Libiih', 'Victor N\'Dip', 'A', 'Build-up', 'Italy 90', 'Maboang'],
    ['medium', "At the 1990 World Cup, Cameroon opened with a 1-0 win over Argentina — who scored Cameroon's goal?", 'François Omam-Biyik', 'Roger Milla', 'André Kana-Biyik', 'Emmanuel Maboang', 'A', 'Opening upset', 'Italy 90', 'Omam-Biyik'],
    ['medium', "At the 1990 World Cup, André Kana-Biyik was sent off vs Argentina — what was the minute?", 'Before half-time', 'After 80 minutes', 'Full time', 'Injury time only', 'A', 'Discipline', 'Italy 90', 'Early'],
    ['medium', "At the 1994 World Cup, Cameroon drew 2-2 with which team in the group stage?", 'Sweden', 'Brazil', 'Russia', 'Bolivia', 'A', 'USA 94', 'Group B', 'Sweden'],
    ['medium', "At the 1994 World Cup, Roger Milla scored in the 5-1 loss to which team?", 'Russia', 'Brazil', 'Sweden', 'Bolivia', 'A', 'Stanford', 'Group B', 'Russia'],
    ['medium', "At the 1982 World Cup, Cameroon drew 0-0 with Poland — who was Poland's star striker?", 'Zbigniew Boniek', 'Grzegorz Lato', 'Andrzej Szarmach', 'Roman Ogaza', 'A', 'Spain 82', 'Group', 'Boniek'],
    ['medium', "At the 1990 World Cup quarter-final, England trailed 2-1 before Lineker's penalties — who scored Cameroon's second goal?", 'Eugène Ekéké', 'Roger Milla', 'Emmanuel Maboang', 'François Omam-Biyik', 'A', 'Naples', 'Extra time', 'Ekéké'],
    ['medium', "At the 1990 World Cup, Cameroon beat Romania 2-1 — Roger Milla scored in that match — true or false?", 'True', 'False', 'Only vs Colombia', 'Only vs England', 'A', 'Bari', 'Group stage', 'True'],
    ['medium', "At the 1994 World Cup, Cameroon lost 6-1 to which team in the group stage?", 'Russia', 'Brazil', 'Sweden', 'Bolivia', 'A', 'Stanford', 'Group B', 'Russia'],
    ['medium', "In 1990, Roger Milla became the oldest goalscorer at a World Cup at that time — how old was he?", '38', '36', '40', '42', 'A', 'Italy 90', 'vs Romania', '38'],
    ['hard', "At the 1934 World Cup, Egypt's Abdulrahman Fawzi scored — which confederation did Egypt represent?", 'Africa', 'Asia', 'Europe', 'CONMEBOL', 'A', 'Italy 34', 'History', 'Africa'],
    ['hard', "At the 1954 World Cup, Pak Doo-ik's goal for South Korea beat Italy — in which city was the match played?", 'Middlesbrough', 'London', 'Liverpool', 'Birmingham', 'A', 'England', 'Venue', 'Middlesbrough'],
    ['hard', "At the 1966 World Cup, North Korea beat Italy 1-0 — who scored the winner?", 'Pak Doo-ik', 'Han Bong-zin', 'Yang Sung-kook', 'Im Seung-hwi', 'A', 'England 66', 'Middlesbrough', 'Pak Doo-ik'],
    ['hard', "At the 1982 World Cup, Algeria beat West Germany 2-1 — who scored Algeria's winning goal?", 'Lakhdar Belloumi', 'Rabah Madjer', 'Salah Assad', 'Tedj Bensaoula', 'A', 'Spain 82', 'Upset', 'Belloumi'],
    ['hard', "At the 1982 World Cup, Algeria beat West Germany 2-1 — who opened the scoring for Algeria?", 'Rabah Madjer', 'Lakhdar Belloumi', 'Salah Assad', 'Tedj Bensaoula', 'A', 'Spain 82', 'First goal', 'Madjer'],
    ['hard', "At the 1990 World Cup, René Higuita was dispossessed by Roger Milla after wandering from goal — which country was Higuita playing for?", 'Colombia', 'Cameroon', 'Brazil', 'Argentina', 'A', 'Naples', 'Goalkeeper error', 'Colombia'],
    ['hard', "At the 1990 World Cup, Roger Milla's second goal vs Colombia came in which minute of extra time?", '106th minute region', '90th minute', '115th minute', '120th minute', 'A', 'Timing', 'Italy 90', 'Extra time'],
    ['hard', "At the 1994 World Cup, Roger Milla's goal vs Russia came in which half?", 'Second half', 'First half', 'Extra time', 'Injury time only', 'A', 'USA 94', 'Timing', 'Second half'],
    ['hard', "At the 1982 World Cup in Spain, Cameroon shared Group 1 with Italy, Poland and which South American opponent?", 'Peru', 'Brazil', 'Argentina', 'Chile', 'A', 'Spain 82', "Milla's debut finals", 'Peru'],
    ['hard', "At the 1990 World Cup, England's Lineker equalised from the penalty spot in extra time vs Cameroon — who fouled for the penalty?", 'Thomas N\'Kono', 'A defender on Lineker', 'Roger Milla', 'No foul', 'B', 'Naples', 'Penalty', 'Foul on Lineker'],
    ['hard', "At the 1994 World Cup, Cameroon faced Brazil in a group match — who scored Brazil's opening goal?", 'Romário', 'Bebeto', 'Rai', 'Mazinho', 'A', 'Stanford', 'Group B', 'Romário'],
  ]),
  'rigobert-song': R([
    ['easy', "At the 1994 World Cup, Rigobert Song was sent off against Brazil — what colour card?", 'Red', 'Yellow', 'Second yellow', 'Blue', 'A', 'USA 94', 'Discipline', 'Red'],
    ['easy', "At the 1994 World Cup, Song became the youngest player sent off in World Cup history at the time — true?", 'True', 'False', 'Only in 1998', 'Only in 2002', 'A', 'Record', 'USA 94', 'True'],
    ['easy', "At the 1998 World Cup, Rigobert Song captained Cameroon — true or false?", 'True', 'False', 'Only vs Italy', 'Only vs Chile', 'A', 'France 98', 'Armband', 'True'],
    ['easy', "At the 2002 World Cup, Song played in Cameroon's group including Germany, Ireland and which team?", 'Saudi Arabia', 'Brazil', 'France', 'Tunisia', 'A', 'Korea/Japan', 'Group E', 'Saudi Arabia'],
    ['easy', "At the 2010 World Cup, Song was in Cameroon's squad — did he start vs Japan?", 'Yes', 'No', 'Only vs Denmark', 'Only vs Netherlands', 'A', 'South Africa', 'Line-up', 'Yes'],
    ['easy', "At the 1998 World Cup, Song played vs Italy — Italy won 3-0 — who scored Italy's second goal?", 'Roberto Baggio', 'Christian Vieri', 'Luigi Di Biagio', 'Paolo Maldini', 'B', 'Montpellier', 'Group B', 'Vieri'],
    ['easy', "At the 2002 World Cup, Song faced Germany as captain — Germany won 2-0 — who scored Germany's second goal?", 'Marco Bode', 'Miroslav Klose', 'Carsten Jancker', 'Michael Ballack', 'A', 'Group E', 'Korea/Japan', 'Bode'],
    ['easy', "How many World Cup finals tournaments did Rigobert Song play in?", 'Four', 'Three', 'Two', 'Five', 'A', '1994–2010', 'Finals', 'Four'],
    ['easy', "At the 1994 World Cup, Song was sent off vs Brazil — Brazil won by what score?", '3-0', '2-0', '1-0', '4-1', 'A', 'Stanford', 'Group B', '3-0'],
    ['easy', "At the 1998 World Cup, Song played against Chile — the match ended 1-1 — who scored for Chile?", 'Marcelo Salas', 'Iván Zamorano', 'Fabián Estay', 'José Luis Sierra', 'A', 'Group B', 'France 98', 'Salas'],
    ['medium', "At the 1994 World Cup, Song's red card vs Brazil came in which half?", 'Second half', 'First half', 'Extra time', 'Before kick-off', 'A', 'USA 94', 'Discipline', 'Second half'],
    ['medium', "At the 1998 World Cup, Song played vs Austria in a 1-1 draw — who scored Austria's goal?", 'Anton Pfeffer', 'Andreas Herzog', 'Ivica Vastić', 'Toni Polster', 'A', 'France 98', 'Group B', 'Pfeffer'],
    ['medium', "At the 2002 World Cup, Song captained Cameroon vs Ireland — the match ended 1-1 — who scored for Ireland?", 'Matt Holland', 'Robbie Keane', 'Damien Duff', 'Jason McAteer', 'A', 'Niigata', 'Group E', 'Holland'],
    ['medium', "At the 2010 World Cup, Song played vs Denmark — Eto'o scored Cameroon's only goal — Song's role was primarily what?", 'Defender', 'Striker', 'Goalkeeper', 'Winger', 'A', 'South Africa', 'Position', 'Defender'],
    ['medium', "At the 1998 World Cup, Song faced Roberto Baggio's Italy — Baggio wore which famous shirt number for Italy?", '10', '9', '7', '11', 'A', 'France 98', 'Number', '10'],
    ['medium', "At the 2002 World Cup, Song played vs Saudi Arabia — Cameroon won 1-0 — who scored?", 'Samuel Eto\'o', 'Patrick Mboma', 'Pierre Womé', 'Salomon Olembe', 'A', 'Saitama', 'Group E', 'Eto\'o'],
    ['medium', "At the 1994 World Cup, Song's Cameroon faced Russia — who scored a hat-trick for Russia in a 6-1 win?", 'Oleg Salenko', 'Dmitri Radchenko', 'Igor Kolyvanov', 'Vladimir Beschastnykh', 'A', 'Stanford', 'Group B', 'Salenko'],
    ['medium', "At the 1998 World Cup, Song played vs Austria's Toni Polster — Polster was known as a what?", 'Forward', 'Goalkeeper', 'Referee', 'Coach', 'A', 'France 98', 'Role', 'Forward'],
    ['medium', "At the 2002 World Cup, Song wore the captain's armband vs Germany — who was Germany's captain?", 'Oliver Kahn', 'Michael Ballack', 'Carsten Ramelow', 'Bernd Schneider', 'A', 'Group E', 'Korea/Japan', 'Kahn'],
    ['medium', "At the 2010 World Cup, Song played his last World Cup match vs Netherlands — Netherlands won 2-1 — who scored Netherlands' first goal?", 'Robin van Persie', 'Arjen Robben', 'Wesley Sneijder', 'Dirk Kuyt', 'A', 'Cape Town', 'Group E', 'Van Persie'],
    ['hard', "At the 1934 World Cup, Egypt's first goal at the finals was scored by whom?", 'Abdulrahman Fawzi', 'Mahmoud Mokhtar', 'Hassan Ragab', 'No Egyptian scored', 'A', 'Italy 34', 'Pioneer', 'Fawzi'],
    ['hard', "At the 1954 World Cup, South Korea conceded nine goals to Hungary — who scored multiple goals for Hungary?", 'Sándor Kocsis', 'Nándor Hidegkuti', 'Ferenc Puskás', 'Zoltán Czibor', 'A', 'Switzerland 54', 'Hungary', 'Kocsis'],
    ['hard', "At the 1982 World Cup, Cameroon's Rigobert Song was not yet in the squad — who captained Cameroon then?", 'Thomas N\'Kono', 'Théophile Abega', 'Jean Manga Onguéné', 'Roger Milla', 'A', 'Spain 82', 'Era', 'N\'Kono'],
    ['hard', "At the 1990 World Cup, Rigobert Song did not play — Cameroon's run included a win over Colombia thanks to whom?", 'Roger Milla', 'François Omam-Biyik', 'Thomas N\'Kono', 'Emmanuel Maboang', 'A', 'Italy 90', 'Before Song era', 'Milla'],
    ['hard', "At the 1994 World Cup, Song was sent off vs Brazil — which Brazilian defender was known for tough tackling that match?", 'Jorginho', 'Márcio Santos', 'Aldair', 'Cafu', 'A', 'USA 94', 'Brazil back line', 'Jorginho'],
    ['hard', "At the 1998 World Cup, Song played vs Marcelo Salas — Salas scored twice vs Cameroon — what was the score?", 'Chile 3-0 Cameroon', '2-1 Chile', '1-1', '2-0 Cameroon', 'A', 'France 98', 'Group B', '3-0'],
    ['hard', "At the 2002 World Cup, Song faced Robbie Keane's Ireland — Keane scored Ireland's goal — minute?", 'First half', 'Second half', 'Extra time', 'Injury time', 'B', 'Niigata', '1-1', 'Second half'],
    ['hard', "At the 2010 World Cup, Song played vs Denmark — which Danish midfielder opened the scoring?", 'Dennis Rommedahl', 'Jon Dahl Tomasson', 'Christian Poulsen', 'Daniel Agger', 'A', 'South Africa', 'Group E', 'Rommedahl'],
    ['hard', "At the 1994 World Cup, Song's red card vs Brazil — who converted a penalty for Brazil in that 3-0 win?", 'Bebeto', 'Romário', 'Rai', 'Mazinho', 'B', 'USA 94', 'Spot kick', 'Romário'],
    ['hard', "At the 1998 World Cup, Song played vs Baggio — Baggio scored Italy's third vs Cameroon — was it a penalty?", 'Yes', 'No', 'Own goal', 'Header only', 'A', 'Montpellier', 'Italy 3-0', 'Penalty'],
    ['hard', "At the 2002 World Cup, Song's Cameroon exited in the group stage — how many points did Cameroon earn?", 'Two', 'Three', 'Four', 'One', 'A', 'Group E', 'Results', 'Two'],
  ]),
};
