const R = (a) => a;

export const senegal = {
  'sadio-mane': R([
    ['easy', "At the 2018 World Cup, Sadio Mané scored Senegal's opening goal in a 2-1 win over which team?", 'Poland', 'Japan', 'Colombia', 'Russia', 'A', 'Russia 2018', 'Group H', 'Poland'],
    ['easy', "At the 2018 World Cup, Mané converted a penalty in Senegal's 2-2 draw with which team?", 'Japan', 'Poland', 'Colombia', 'England', 'A', 'Group H', 'Samara', 'Japan'],
    ['easy', "At the 2018 World Cup, did Sadio Mané play at the finals in Qatar 2022?", 'No — he missed the tournament through injury', 'Yes', 'Only as a coach', 'Only in qualifiers', 'A', 'Senegal 2022', 'Injury before finals', 'Did not play'],
    ['easy', "At the 2018 World Cup, Mané faced Colombia in the group — Colombia won 1-0 — who scored Colombia's goal?", 'Yerry Mina', 'Radamel Falcao', 'Juan Cuadrado', 'James Rodríguez', 'A', 'Samara', 'Group H', 'Mina'],
    ['easy', "At the 2018 World Cup, Mané wore which shirt number for Senegal?", '10', '9', '7', '11', 'A', 'Russia', 'Squad number', '10'],
    ['easy', "At the 2018 World Cup, Senegal exited on fair play after a 1-0 loss to which team?", 'Colombia', 'Japan', 'Poland', 'England', 'A', 'Group decider', 'Samara', 'Colombia'],
    ['easy', "At the 2018 World Cup, Mané started vs Japan — what was the final score?", '2-2', '1-0 Senegal', '3-1 Japan', '0-0', 'A', 'Ekaterinburg', 'Group H', '2-2'],
    ['easy', "At the 2018 World Cup, Mané scored vs Poland — was his goal from open play or a penalty?", 'Penalty', 'Open play', 'Header', 'Own goal', 'A', 'Moscow', 'Spot kick', 'Penalty'],
    ['easy', "At the 2018 World Cup, Senegal were eliminated in the group stage — Mané's final group match was against which team?", 'Colombia', 'Japan', 'Poland', 'England', 'A', 'Samara', 'Group H', 'Colombia'],
    ['easy', "At the 2018 World Cup, Mané's Senegal beat Poland 2-1 — who scored Poland's consolation goal?", 'Grzegorz Krychowiak', 'Robert Lewandowski', 'Arkadiusz Milik', 'Kamil Grosicki', 'A', 'Spartak Stadium', 'Group H', 'Krychowiak'],
    ['medium', "At the 2018 World Cup, Mané faced Jan Bednarek's Poland — Lewandowski played — did Mané score from the penalty spot?", 'Yes', 'No', 'Only vs Japan', 'Only vs Colombia', 'A', 'Poland match', 'Russia 2018', 'Yes'],
    ['medium', "At the 2018 World Cup, Senegal's fair-play exit meant Japan advanced — Senegal had how many yellow cards in the group?", 'More than Japan', 'Fewer than Japan', 'Same as Japan', 'Zero', 'A', 'Tiebreaker', 'Group H', 'Discipline'],
    ['medium', "At the 2002 World Cup, Senegal reached the quarter-finals — Mané was a child — who scored the winner vs Sweden in extra time?", 'Henri Camara', 'El Hadji Diouf', 'Papa Bouba Diop', 'Khalilou Fadiga', 'A', 'Japan/Korea', 'Golden goal', 'Camara'],
    ['medium', "At the 2002 World Cup, Senegal beat France 1-0 — who scored Senegal's goal?", 'Papa Bouba Diop', 'El Hadji Diouf', 'Salif Diao', 'Henri Camara', 'A', 'Seoul', 'Opening match', 'Bouba Diop'],
    ['medium', "At the 1986 World Cup, Senegal did not qualify — Cameroon's Roger Milla scored at Italy 1990 — Senegal's first WC was which year?", '2002', '1994', '1998', '2018', 'A', 'History', 'Debut', '2002'],
    ['medium', "At the 2018 World Cup, Mané played vs Colombia's James Rodríguez — James started on the bench that day — true?", 'True', 'False', 'James did not play', 'James scored twice', 'A', 'Samara', 'Line-ups', 'True'],
    ['medium', "At the 2018 World Cup, Mané's shot vs Japan led to a handball check — the match ended 2-2 — who scored Japan's second?", 'Keisuke Honda', 'Shinji Kagawa', 'Genki Haraguchi', 'Takashi Inui', 'A', 'Ekaterinburg', 'Group H', 'Honda'],
    ['medium', "At the 2018 World Cup, Mané faced Wojciech Szczęsny in goal for Poland — Senegal won 2-1 — who assisted Mané's goal?", 'Idrissa Gueye', 'Badou Ndiaye', 'Cheikhou Kouyaté', 'Kalidou Koulibaly', 'A', 'Build-up', 'Poland', 'Gueye'],
    ['medium', "At the 2018 World Cup, Mané played in every Senegal group match — how many goals did he score?", 'One', 'Two', 'Three', 'Zero', 'B', 'Russia', 'Tally', 'Two'],
    ['medium', "At the 2018 World Cup, Mané's Senegal faced Japan — Inui scored a curling goal — was it Japan's first equaliser?", 'Yes', 'No', 'Only goal', 'Own goal', 'A', '2-2', 'Samara', 'Yes'],
    ['hard', "At the 1934 World Cup, Egypt's Abdulrahman Fawzi scored — which continent was Egypt representing?", 'Africa', 'Asia', 'Europe', 'Oceania', 'A', 'Italy 34', 'Pioneer', 'Africa'],
    ['hard', "At the 1954 World Cup, Pak Doo-ik scored for South Korea vs Italy — Italy had won which World Cups before?", '1934 and 1938', '1950', 'None', '1966', 'A', 'Switzerland 54', 'History', 'Two'],
    ['hard', "At the 2002 World Cup, Senegal's Camara scored vs Sweden — was the goal in extra time?", 'Yes — golden goal', 'No — penalties', 'No — full time', 'Own goal', 'A', 'Round of 16', 'Japan/Korea', 'Golden goal'],
    ['hard', "At the 2018 World Cup, Mané was fouled for a penalty vs Japan — who took Senegal's second penalty of the tournament?", 'Mané', 'Balde', 'Niang', 'Sarr', 'A', 'Spot kicks', 'Japan', 'Mané'],
    ['hard', "At the 2018 World Cup, Mané played vs Colombia — Falcao headed chances — who kept goal for Senegal?", 'Khadim N\'Diaye', 'Alfred Gomis', 'Abdoulaye Diallo', 'Édouard Mendy', 'A', 'Not at 2018', 'Russia 2018', 'N\'Diaye'],
    ['hard', "At the 2018 World Cup, Senegal needed a result vs Colombia — Yerry Mina's header eliminated Senegal — minute?", '74th minute', '90th minute', 'First half', 'Extra time', 'A', 'Samara', 'Header', '74'],
    ['hard', "At the 2018 World Cup, Mané's dribble drew defenders vs Japan — Senegal's second goal was an own goal — true?", 'False', 'True', 'Only vs Poland', 'Only vs Colombia', 'A', '2-2 Japan', 'Scorers', 'Both teams scored normally'],
    ['hard', "At the 2018 World Cup, Mané faced Robert Lewandowski — did Lewandowski score vs Senegal?", 'No', 'Yes', 'Penalty', 'Hat-trick', 'A', 'Poland 1-2', 'Lewandowski', 'No'],
    ['hard', "At the 2018 World Cup, Mané played in Russia — Senegal's coach was who?", 'Aliou Cissé', 'Bruno Metsu', 'Alain Giresse', 'Claude Le Roy', 'A', 'Dugout', 'Russia 2018', 'Cissé'],
    ['hard', "At the 2018 World Cup, Senegal failed to reach the round of 16 — Japan advanced on fair play tiebreakers — true?", 'True', 'False', 'Senegal advanced', 'Coin toss', 'A', 'Fair play', 'Group H', 'True'],
    ['hard', "At the 2018 World Cup, Senegal were eliminated in the group stage on fair play — Mané's last action was vs which team?", 'Colombia', 'Japan', 'Poland', 'England', 'A', 'Group stage', 'Russia 2018', 'Colombia'],
  ]),
  'el-hadji-diouf': R([
    ['easy', "At the 2002 World Cup, El Hadji Diouf started Senegal's shock 1-0 win over France — who scored Senegal's goal?", 'Papa Bouba Diop', 'Diouf', 'Henri Camara', 'Khalilou Fadiga', 'A', 'Seoul', 'Opening match', 'Bouba Diop'],
    ['easy', "At the 2002 World Cup, who won the Golden Ball — not Diouf?", 'Oliver Kahn', 'Ronaldo', 'Oliver Neuville', 'Landon Donovan', 'A', 'Awards', 'Korea/Japan', 'Kahn'],
    ['easy', "At the 2002 World Cup, Diouf assisted or created danger vs Denmark — Senegal drew 1-1 — who scored Senegal's goal?", 'Salif Diao', 'Papa Bouba Diop', 'Khalilou Fadiga', 'Henri Camara', 'A', 'Daegu', 'Group A', 'Salif Diao'],
    ['easy', "At the 2002 World Cup, Senegal drew 3-3 with Uruguay — how many goals did Senegal score?", 'Three', 'Two', 'Four', 'One', 'A', 'Suwon', 'Group A', 'Three'],
    ['easy', "At the 2002 World Cup, Diouf faced Fabien Barthez in Senegal's win over France — did Diouf score?", 'No', 'Yes', 'Penalty', 'Own goal', 'A', 'Seoul', 'France 0-1', 'No'],
    ['easy', "At the 2002 World Cup, Senegal reached the quarter-finals — they lost 1-0 to which team?", 'Turkey', 'Brazil', 'South Korea', 'Germany', 'A', 'Osaka', 'Quarter-final', 'Turkey'],
    ['easy', "At the 2002 World Cup, Diouf faced Uruguay — Senegal fought back for 3-3 — who scored Uruguay's third goal?", 'Richard Morales', 'Diego Forlán', 'Álvaro Recoba', 'Dario Silva', 'A', 'Suwon', 'Group A', 'Morales'],
    ['easy', "At the 2002 World Cup, Diouf's dribbling vs France drew fouls from which French defender?", 'Frank Leboeuf', 'Marcel Desailly', 'Lilian Thuram', 'Bixente Lizarazu', 'A', 'Seoul', 'France', 'Leboeuf'],
    ['easy', "At the 2002 World Cup, Senegal drew 1-1 with Denmark — Thomas Sørensen saved for Denmark — true?", 'True', 'False', 'Only vs France', 'Only vs Uruguay', 'A', 'Daegu', 'Goalkeeper', 'True'],
    ['easy', "At the 2002 World Cup, Diouf played in the round of 16 vs Sweden — the match went to extra time — who scored the golden goal?", 'Henri Camara', 'Papa Bouba Diop', 'El Hadji Diouf', 'Khalilou Fadiga', 'A', 'Oita', 'Golden goal', 'Camara'],
    ['medium', "At the 2002 World Cup, Diouf faced Zinedine Zidane injured on the bench vs France — Zidane missed the opener — true?", 'True', 'False', 'Zidane scored', 'Zidane sent off', 'A', 'France 0-1', 'Injury', 'True'],
    ['medium', "At the 2002 World Cup, Senegal beat Sweden 2-1 after extra time — Camara scored — was Diouf substituted?", 'Yes', 'No', 'Only in final', 'Red card', 'A', 'Extra time', 'Knockout', 'Yes'],
    ['medium', "At the 2002 World Cup, Diouf played vs Turkey in the quarter-final — İlhan Mansız scored the golden goal — minute?", '94th minute', '80th minute', '105th minute', '120th minute', 'A', 'Osaka', 'Turkey 1-0', 'Golden goal'],
    ['medium', "At the 2002 World Cup, Diouf's Senegal topped Group A ahead of which teams?", 'Denmark, Uruguay, France', 'France only', 'Brazil', 'Spain', 'A', 'Standings', 'Group A', 'Three teams'],
    ['medium', "At the 2002 World Cup, Diouf wore which shirt number?", '11', '10', '9', '7', 'A', 'Senegal', 'Squad', '11'],
    ['medium', "At the 2002 World Cup, Diouf faced Forlán and Recoba — Uruguay scored three — who scored Uruguay's third?", 'Richard Morales', 'Diego Forlán', 'Álvaro Recoba', 'Dario Silva', 'A', 'Suwon', '3-3', 'Morales'],
    ['medium', "At the 2002 World Cup, Senegal's Khalilou Fadiga scored a penalty vs Uruguay — was Diouf involved in the foul won?", 'Penalty awarded', 'Direct free kick', 'Corner', 'No penalty', 'A', 'Suwon', 'Spot kick', 'Penalty'],
    ['medium', "At the 2002 World Cup, Diouf played vs Thomas Gravesen for Denmark — Gravesen was known as a what?", 'Midfield enforcer', 'Goalkeeper', 'Striker', 'Referee', 'A', 'Daegu', 'Denmark', 'Midfielder'],
    ['medium', "At the 2002 World Cup, Diouf's Senegal eliminated Sweden — was the Sweden keeper Magnus Hedman?", 'Yes', 'No', 'Ravelli', 'Isaksson', 'A', 'Oita', 'Sweden', 'Hedman'],
    ['medium', "At the 2002 World Cup, Diouf faced Rüştü Reçber's Turkey — Turkey finished third — true?", 'Third place', 'Fourth', 'Winners', 'Group exit', 'A', 'Korea/Japan', 'Turkey', 'Third'],
    ['hard', "At the 1934 World Cup, Egypt scored — who was in goal for Hungary vs Egypt?", 'Antal Szabó', 'Gyula Grosics', 'Ferenc Plattkó', 'Béla Kállai', 'A', 'Italy 34', 'Goalkeepers', 'Szabó'],
    ['hard', "At the 1954 World Cup, South Korea's Pak Doo-ik beat Italy — Italy's keeper was?", 'Giorgio Ghezzi', 'Lorenzo Buffon', 'Carlo Mattrel', 'Giampiero Boniperti', 'A', 'Switzerland 54', 'Italy', 'Ghezzi'],
    ['hard', "At the 2002 World Cup, Diouf's run vs France created space — Bouba Diop scored — was Diop's goal the only shot on target?", 'One of few', 'Twenty shots', 'Zero', 'Only own goal', 'A', 'Seoul', 'Narrative', 'Few chances'],
    ['hard', "At the 2002 World Cup, Diouf was booked in the tournament — true?", 'True', 'False', 'Sent off', 'Never fouled', 'A', 'Discipline', 'Japan/Korea', 'True'],
    ['hard', "At the 2002 World Cup, Senegal's Bruno Metsu was manager — did Diouf dedicate runs to Metsu?", 'Media stories', 'No', 'Only after 2010', 'Only vs Brazil', 'A', 'Coach', 'Legacy', 'Team'],
    ['hard', "At the 2002 World Cup, Diouf faced Fabien Barthez — Barthez conceded once — was it from open play?", 'Yes', 'No', 'Penalty', 'Own goal', 'A', 'Seoul', 'Goal', 'Open play'],
    ['hard', "At the 2002 World Cup, Diouf played vs Sweden — Anders Svensson scored a free-kick — did Senegal equalise before extra time?", 'Yes', 'No', 'Only in penalties', '0-0 full time', 'A', 'Oita', 'Sweden 1-1', 'Yes'],
    ['hard', "At the 2002 World Cup, Diouf's last match was vs Turkey — İlhan Mansız scored — was Diouf substituted?", 'Yes', 'No', 'Injury', 'Red card', 'A', 'Quarter-final', 'Osaka', 'Yes'],
    ['hard', "At the 2002 World Cup, Diouf faced Hakan Şükür's Turkey — Şükür later scored the fastest World Cup goal — was that in 2002?", 'Yes vs South Korea third-place', 'No', '1998', '2010', 'A', 'Fastest goal', 'Third place match', '2002'],
    ['hard', "At the 2002 World Cup, Diouf's Senegal beat France — Vieira and Petit started — who captained France?", 'Marcel Desailly', 'Zidane', 'Barthez', 'Thuram', 'A', 'France', 'Armband', 'Desailly'],
    ['hard', "At the 2002 World Cup, Diouf played every knockout minute until sub vs Turkey — true?", 'False — subbed', 'True', 'Only vs Sweden', 'Never subbed', 'A', 'Minutes', 'Osaka', 'Subbed'],
  ]),
  'kalidou-koulibaly': R([
    ['easy', "At the 2022 World Cup, Kalidou Koulibaly scored a crucial winner against which team to send Senegal through?", 'Ecuador', 'Netherlands', 'Qatar', 'Iran', 'A', 'Qatar 2022', 'Group A', 'Ecuador'],
    ['easy', "At the 2022 World Cup, Koulibaly wore the captain's armband for Senegal — true?", 'True', 'False', 'Only vs Netherlands', 'Only vs Qatar', 'A', 'Leadership', 'Qatar', 'True'],
    ['easy', "At the 2018 World Cup, Koulibaly started in defence — Senegal faced Japan in a 2-2 draw — did Koulibaly score?", 'No', 'Yes', 'Own goal', 'Penalty', 'A', 'Russia 2018', 'Defender', 'No'],
    ['easy', "At the 2022 World Cup, Koulibaly played vs Netherlands — Netherlands won 2-0 — who scored the first goal?", 'Cody Gakpo', 'Memphis Depay', 'Davy Klaassen', 'Frenkie de Jong', 'A', 'Group A', 'Qatar', 'Gakpo'],
    ['easy', "At the 2022 World Cup, Koulibaly helped Senegal beat Qatar 3-1 — who scored Senegal's third?", 'Bamba Dieng', 'Famara Diédhiou', 'Ismaïla Sarr', 'Boulaye Dia', 'A', 'Doha', 'Group A', 'Dieng'],
    ['easy', "At the 2018 World Cup, Koulibaly played vs Colombia — Senegal lost 1-0 — who scored?", 'Yerry Mina', 'Falcao', 'Cuadrado', 'James', 'A', 'Samara', 'Russia 2018', 'Mina'],
    ['easy', "At the 2022 World Cup, Koulibaly's goal vs Ecuador was a shot from inside the box after a set-piece scramble — true?", 'True', 'False', 'Header from corner', 'Own goal', 'A', 'Winner', 'Group A', 'True'],
    ['easy', "At the 2022 World Cup, Koulibaly faced Enner Valencia's Ecuador — Valencia had scored earlier in the tournament — did Valencia score vs Senegal?", 'Yes', 'No', 'Twice', 'Hat-trick', 'A', 'Must-win', 'Ecuador', 'Yes'],
    ['easy', "At the 2018 World Cup, Koulibaly played vs Poland — Senegal won 2-1 — was Koulibaly booked?", 'Yes', 'No', 'Sent off', 'Two yellows', 'A', 'Discipline', 'Russia', 'Yes'],
    ['easy', "At the 2022 World Cup, Koulibaly played in the round of 16 — Senegal lost 3-0 to which team?", 'England', 'France', 'Brazil', 'Spain', 'A', 'Qatar', 'Knockout', 'England'],
    ['medium', "At the 2022 World Cup, Koulibaly's winner vs Ecuador came in which half?", 'Second half', 'First half', 'Extra time', 'Injury time only', 'A', 'Khalifa', 'Group A', 'Second half'],
    ['medium', "At the 2018 World Cup, Koulibaly blocked shots vs Japan — Japan's second goal was scored by whom?", 'Keisuke Honda', 'Genki Haraguchi', 'Shinji Kagawa', 'Takashi Inui', 'A', 'Ekaterinburg', '2-2', 'Honda'],
    ['medium', "At the 2022 World Cup, Koulibaly faced Virgil van Dijk's Netherlands — Van Dijk captained Netherlands — true?", 'True', 'False', 'De Jong captained', 'Blind captained', 'A', 'Group A', 'Qatar', 'True'],
    ['medium', "At the 2002 World Cup, Senegal reached the quarter-finals — Koulibaly was a youth — who managed Senegal then?", 'Bruno Metsu', 'Aliou Cissé', 'Claude Le Roy', 'Lamine N\'Diaye', 'A', 'History', 'Japan/Korea', 'Metsu'],
    ['medium', "At the 2022 World Cup, Koulibaly played vs Qatar — Qatar scored their first World Cup goal — who scored for Qatar?", 'Mohammed Muntari', 'Almoez Ali', 'Akram Afif', 'Hassan Al-Haydos', 'A', 'Group A', 'Hosts', 'Muntari'],
    ['medium', "At the 2018 World Cup, Koulibaly partnered with Salif Sané in defence — vs Japan — did Sané score?", 'No', 'Yes', 'Own goal', 'Penalty', 'A', 'Russia', 'Centre-backs', 'No'],
    ['medium', "At the 2022 World Cup, Koulibaly faced Moisés Caicedo's Ecuador — Caicedo equalised before Koulibaly's winner — true?", 'True', 'False', 'No equaliser', 'Only penalties', 'A', '2-1 Senegal', 'Group A', 'True'],
    ['medium', "At the 2022 World Cup, Koulibaly played vs England — England's first goal was a penalty by whom?", 'Harry Kane', 'Marcus Rashford', 'Bukayo Saka', 'Phil Foden', 'A', 'Round of 16', 'Qatar', 'Kane'],
    ['medium', "At the 2018 World Cup, Koulibaly's Senegal kept one clean sheet in the group — vs which team?", 'No clean sheet', 'Japan', 'Poland', 'Colombia', 'A', 'Goals conceded', 'Russia 2018', 'No clean sheet'],
    ['medium', "At the 2022 World Cup, Koulibaly scored with his weaker foot vs Ecuador — right or left?", 'Left foot', 'Right foot', 'Header', 'Knee', 'A', 'Strike', 'Winner', 'Left'],
    ['hard', "At the 1934 World Cup, Egypt conceded to Hungary — how many goals did Hungary score?", 'Four', 'Two', 'Three', 'Five', 'A', 'Italy 34', 'Scoreline', 'Four'],
    ['hard', "At the 1954 World Cup, South Korea's Pak Doo-ik scored — was the shot with the left foot?", 'Right foot', 'Left foot', 'Header', 'Backheel', 'B', 'Italy', 'Middlesbrough', 'Left foot'],
    ['hard', "At the 2002 World Cup, Senegal's goalkeeper in the quarter-final vs Turkey was whom?", 'Tony Sylva', 'Édouard Mendy', 'Khadim N\'Diaye', 'Bouna Coundoul', 'A', 'Japan/Korea', 'Shot-stopper', 'Sylva'],
    ['hard', "At the 2022 World Cup, Koulibaly's Napoli career is irrelevant — did he head the winner vs Ecuador?", 'Volley / strike', 'Header', 'Knee', 'Backheel', 'A', 'Technique', 'Winner', 'Strike'],
    ['hard', "At the 2022 World Cup, Koulibaly faced Piero Hincapié's Ecuador — Hincapié was booked — true?", 'True', 'False', 'Sent off', 'Goal', 'A', 'Discipline', 'Group A', 'True'],
    ['hard', "At the 2018 World Cup, Koulibaly played vs James Rodríguez — James assisted Mina — was Koulibaly marking Mina on the corner?", 'Set-piece chaos', 'Always man-marking', 'Offside', 'Never', 'A', 'Colombia goal', 'Samara', 'Corner'],
    ['hard', "At the 2022 World Cup, Koulibaly's Senegal faced Netherlands — first goal Gakpo — was it a header?", 'Header', 'Shot', 'Penalty', 'Own goal', 'A', 'Opening goal', 'Group A', 'Header'],
    ['hard', "At the 2022 World Cup, Koulibaly played every minute of the group stage — true?", 'False', 'True', 'Only vs Qatar', 'Subbed every game', 'A', 'Minutes', 'Qatar', 'Rotation'],
    ['hard', "At the 2022 World Cup, Koulibaly's winner vs Ecuador eliminated which team?", 'Ecuador', 'Senegal', 'Netherlands', 'Qatar', 'A', 'Table', 'Group A', 'Ecuador'],
    ['hard', "At the 2018 World Cup, Koulibaly's long clearances vs Japan — Honda equalised from a set-piece — minute?", 'Injury time', 'First half', 'Half-time', '15th minute', 'A', '2-2', 'Honda', 'Injury time'],
    ['hard', "At the 2022 World Cup, Koulibaly faced Jude Bellingham's England — Bellingham assisted goals — Senegal lost 3-0 — who scored England's third?", 'Bukayo Saka', 'Harry Kane', 'Phil Foden', 'Jack Grealish', 'A', 'Round of 16', 'Qatar', 'Saka'],
  ]),
};
